### PR TITLE
Edit Distance Problem

### PR DESCRIPTION
**Pull request by viveknathani**
Hi guys! I saw that the algorithm for this was missing from the collection of dynamic programming algorithms. So I went ahead and wrote this.

### CODE REVIEW

**Review by raklaptudirm — APPROVED** [review]

**Comment by viveknathani** [comment]
Hey! Thanks for the review so far. It would be amazing if you could add the `hacktoberfest-accepted`  label to this PR. Thanks in advance!

**Comment by raklaptudirm** [comment]
@viveknathani I need to wait for the other maintainers reviews before we can do that.

**Comment by raklaptudirm** [comment]
@siriak So you are approving this pr? We need another review to merge this.

**Comment by siriak** [comment]
I'll review later or @tjgurwara99  can review, but looks good at the first glance

**Review by siriak — APPROVED** [review]

**Pull request merged**
