### PR TITLE
style: use consistent naming

### PR DESCRIPTION
**Pull request by vil02**
#### Description of Change

The file [`romantointeger.go`](https://github.com/TheAlgorithms/Go/blob/b8648fb231848af1a418cda6d8fa8b7b85e09694/conversion/romantointeger.go) contains a function `RomanToInteger` and the file [`integertoroman.go`](https://github.com/TheAlgorithms/Go/blob/b8648fb231848af1a418cda6d8fa8b7b85e09694/conversion/integertoroman.go) defines its _inverse_ `IntToRoman`. I think it is worth having a consistent naming here. ~~Based on the filenames, I suggest to rename `IntToRoman` to `IntegerToRoman`~~. This PR renames the function `RomanToInteger` to `RomanToInt` and renames the corresponding source files.

#### Checklist

- [x] Added description of change
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/Go/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
Rename `RomanToInteger`to `RomanToInt`.

### CODE REVIEW

**Review by tjgurwara99 — COMMENTED** [review]
I'd rather prefer you went the other way and modified the name of `RomanToInteger` to `RomanToInt`.

**Comment by siriak** [comment]
Agree with Taj, it's common to use Int for Integer and this should be clear to everybody

**Comment by vil02** [comment]
@tjgurwara99 @siriak should I also rename the source files?

**Comment by tjgurwara99** [comment]
Yeah go ahead @vil02 😄

**Comment by vil02** [comment]
@tjgurwara99 @siriak Please have a look.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Review by tjgurwara99 — APPROVED** [review]

**Comment by vil02** [comment]
@tjgurwara99 @siriak I have noticed that after this change, there are some _dead_ links in the [`README.md`](https://github.com/TheAlgorithms/Go/blob/4b49179e8ace094c03fde0b652c5fc7eb1d79e4f/README.md). Why is the [`Generate Documentation`](https://github.com/TheAlgorithms/Go/blob/master/.github/workflows/godocmd.yml) not active?

**Comment by siriak** [comment]
I've re-enabled the workflow and the links should be fine now. Why was it disabled, though?

**Pull request merged**
