### PR TITLE
add bogo sort

### PR DESCRIPTION
**Pull request by suhailmalik07**
This PR adds bogo sort.

### CODE REVIEW

**Comment by suhailmalik07** [comment]
Wasn't able to add it into sorts_test.go as it takes a lot time even for 20 elements array (tried 120s, got timeout).

Let me know if anything better can be done.

**Comment by tjgurwara99** [comment]
Just passing by, will review it later but I think you can still write the test for it and add the `t.Skip()` call in the beginning of the test to skip it. Bogo sort is one of those algorithms that's fun to think about but not really good for CI and their associated compute power spent.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Comment by siriak** [comment]
@tjgurwara99 could you review?

**Review by tjgurwara99 — APPROVED** [review]

**Pull request merged**
