### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by kartikay23**
Created readme file for sorting

### CODE REVIEW

**Comment by raklaptudirm** [comment]
Documentation is provided in comments in my opinion.

**Comment by kartikay23** [comment]
I create readme file for sorting as an overview about it. People can see it as an overview of the topic if they do not want yo go side each file.

**Comment by raklaptudirm** [comment]
I will wait for the opinion of the other maintainers before approving this.

**Comment by tjgurwara99** [comment]
I also think this is unnecessary - people can just go to [this](https://pkg.go.dev/github.com/TheAlgorithms/Go@v0.0.2-alpha/sort) and get a much better overview of all the algorithms. I don't mind keeping this readme though either but overtime (from my experience I know that) this will get out of date very quickly.

**Comment by siriak** [comment]
It seems that there are better options than adding readme, but thanks anyway!

**Pull request closed without merging**
