### PR TITLE
feat: max func without using conditional operators

### PR DESCRIPTION
**Pull request by i-redbyte**
add an algorithm for finding the maximum number without using conditional operators

### CODE REVIEW

**Review by raklaptudirm — CHANGES_REQUESTED** [review]
I would suggest renaming it to `bitwiseMax`.

**Comment by i-redbyte** [comment]
> I would suggest renaming it to `bitwiseMax`.

fixed it

**Review by raklaptudirm — APPROVED** [review]

**Comment by i-redbyte** [comment]
and who is merging the pull request?

**Review by siriak — APPROVED** [review]
LGTM, thanks! I'm merging it :)

**Pull request merged**
