### PR TITLE
add btree test file

### PR DESCRIPTION
**Pull request by FemiNoviaLina**
Hi, I added a test file for some functions in binary tree.  I can't write test for traversal (in-order, pre-order, post-order, level order) because it is not testable (at least that's what I thought). I can update the function and write the test if you want me to do.  If not please consider to review this one. Thank you!

### CODE REVIEW

**Review by tjgurwara99 — APPROVED** [review]
LGMT

**Comment by tjgurwara99** [comment]
It would be great if you could write the tests for traversal as well - in a different Pull Request. Feel free to change the implementation of it if you think it is lacking and can be improved such that it can easily be tested.

**Comment by FemiNoviaLina** [comment]
> It would be great if you could write the tests for traversal as well - in a different Pull Request. Feel free to change the implementation of it if you think it is lacking and can be improved such that it can easily be tested.

Thank you so much for reviewing. I'll send the PR for the traversal soon.

**Review by raklaptudirm — APPROVED** [review]
Just @tjgurwara99 's changes.

**Pull request merged**
