### PR TITLE
Add polybius cipher

### PR DESCRIPTION
**Pull request by cfvescovo**

### CODE REVIEW

**Comment by nomisrevol** [comment]
Could you implement unit test for this?

**Comment by task4233** [comment]
@cfvescovo , @nomisrevol 
Hello.
Since I wrote the test for this pull request, I pushed to this branch, `$ git push cfvescovo HEAD:polybius`.
However, my pushing was denied because of permission.

Then, Should I create new pull request which refers this pull request?
Or is there some other solution?
I would appreciate it if you could tell me about that.

Thanks in advance.

**Comment by nomisrevol** [comment]
@task4233 That's okay. Just push into a new pull request and mention (link to) this pull request also. I will have a look on both. Thank you.

**Comment by task4233** [comment]
@nomisrevol
Thanks for helping for me.
I've pushed into a new pull request(#259 ).

**Pull request closed without merging**
