### PR TITLE
update bubblesort swap

### PR DESCRIPTION
**Pull request by qzqsmile**
Go go swap array variable quickly, no need to implement a swap function.

### CODE REVIEW

**Comment by hollypop4u** [comment]
Pls i need how to clone a sim card

**Comment by hollypop4u** [comment]
Pls i need how to clone a sim card

**Comment by rajneesh44** [comment]
@cclauss @StepfenShawn I feel this PR needs to be merged? Shall I do it?

**Comment by cclauss** [comment]
Sure.  How are we testing Go algorithms to ensure that they do what they claim it do?

**Comment by rajneesh44** [comment]
The previous code of bubble sort was in working condition and @qzqsmile has only changed the way of swapping and this works in Go.

For reference: https://stackoverflow.com/questions/38571354/best-way-to-swap-variable-values-in-go#:~:text=There%20is%20a%20function%20called,index%20values%20in%20the%20slice.&text=Yes%2C%20you%20can%20swap%20values%20like%20python.

**Comment by cclauss** [comment]
Thanks.  Are there other files in this repo that you want to create tests for?

**Comment by rajneesh44** [comment]
@cclauss Yes, we need test files for many directories such as ciphers, Dynamic Programming etc. Do you think I should create an issue and ask people on gitter to contribute?

**Comment by cclauss** [comment]
Sounds like a good plan.  Please add a markdown checklist so we can keep track of progress.
* [ ] ciphers
* [ ] data-structures
* [ ] dynamic-programming
* [ ] other
* [ ] searches
* [x] sorts
* [ ] strings

Please also add a `Help Wanted` tag to the issue.  Thanks.

**Comment by rajneesh44** [comment]
@cclauss Do I have to add the markdown in the issue?

**Comment by cclauss** [comment]
Yes please.

**Pull request merged**
