### PR TITLE
Create eulerTotientFunction.go

### PR DESCRIPTION
**Pull request by vedantmamgain**

### CODE REVIEW

**Comment by vedantmamgain** [comment]
@nomisrevol  You mind taking a look at this.

**Comment by vedantmamgain** [comment]
@Mystigan Check this.

**Comment by vedantmamgain** [comment]
@Mystigan What's causing the lint to fail here ?

**Comment by Mystigan** [comment]
> @Mystigan What's causing the lint to fail here ?

Do not worry. The check fails for two of the programs in "strings" folder and not your changes. 
This has been fixed in my PR  #219 . But all PRs opened before it will still fail the lint. I have mentioned this in our discussion [here.](https://github.com/TheAlgorithms/Go/issues/198#issuecomment-706856393)

**Comment by vedantmamgain** [comment]
@Mystigan Should I go ahead merging it or create a new PR.

**Pull request closed without merging**
