### PR TITLE
Fix: A few structural changes to the repository and added missing tests and fixed some failing tests.

### PR DESCRIPTION
**Pull request by tjgurwara99**
Apologies for the big PR, I tried to make minimal changes but one change/fix lead to another broken thing so... here we are.

I have made a few changes to the repo and added RSA algorithm that was failing tests and had an incorrect implementation.

This is a big PR because I have changed some of the directory structure inside the repo. For example, it made more sense to call the modular exponentiation function as `modular.Exponentiation` than `modular_arithmetic.ModularExponentiation` which was done before (by me). Similar thing applies to `cipher` directories different ciphers. 

I have also added a few algorithms that were needed for the RSA algorithm in the relevant directories, example `modular.Inverse`.

I also noticed that the sorting algorithms tests were not set up correctly and because of which every test passed even though the algorithms were incorrect, example `QuickSort` and `RadixSort`. Unfortunately however, because of the way I have fixed it, it has resulted in `golangci-lint` failing because of one of their [open issue](https://github.com/golangci/golangci-lint/issues/826). I can fix it by changing the implementation but I think we should try and stick to go's ecosystem and use the tools provided by go team, that is `golint`. `golint` is much more stricter than golangci-lint in most cases (as far as I have seen and I think its a good thing). These tools are actually more strict and have a better overall effect on other go tools. But if the maintainers want me to fix it as it is, I will fix it - albeit the code will be a bit uglier.

Closes: #152
Closes: #303

---

The following are open issues that are actually fixed adding it here so that merge automatically closes these issues
Closes: #37
by #266
Closes: #269
by #324
Closes: #36 
by #266

### CODE REVIEW

**Comment by siriak** [comment]
Let's switch to `golint` if it's stricter and more robust. Could you update the `golang_lint_ant_test` script in this PR?

**Comment by tjgurwara99** [comment]
@siriak I looked into it and the go team have archived golint for some reason (about 4 months ago) so its highly unlikely that they will make progress in it. There are other tools that I can look at, would you like me to?

**Comment by tjgurwara99** [comment]
[this](https://github.com/reviewdog/action-staticcheck) seems to be a good alternative.

**Comment by cclauss** [comment]
https://pkg.go.dev/golang.org/x/lint is deprecated and frozen.

**Comment by tjgurwara99** [comment]
> https://pkg.go.dev/golang.org/x/lint is deprecated and frozen.

Yeah, and unfortunately there is no stand in replacement for it.

**Comment by cclauss** [comment]
My vote would be that we stick with https://github.com/golangci/golangci-lint which continues to be well maintained.

**Review by raklaptudirm — DISMISSED** [review]

**Review by raklaptudirm — APPROVED** [review]

**Review by raklaptudirm — APPROVED** [review]

**Review by siriak — APPROVED** [review]
LGTM

**Comment by siriak** [comment]
@tjgurwara99 could you resolve the conflicts so that I could merge?

**Review by siriak — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
