### PR TITLE
test: improve coverage on hashmap package

### PR DESCRIPTION
**Pull request by mcaci**
Hello, I'm creating a separate PR to improve the coverage of the hashmap package in order to test the resize of the hashmap. Hope this can help!
Cheers,
Michele

### CODE REVIEW

**Review by raklaptudirm — DISMISSED** [review]

**Comment by mcaci** [comment]
Hi all, do you have any comments about my answer to the review? Does it make sense to you? I'm ready to revert my changes as in the review, but first I wanted to discuss about my reply to see in which direction we should go with the code

**Comment by tjgurwara99** [comment]
@mcaci I don't see any replies

**Comment by mcaci** [comment]
I updated the comment where i wrote my reply with your handle, maybe it helps finding it. If not I just copy/paste it below. Let me know if it worked.

**Comment by tjgurwara99** [comment]
@mcaci I still don't see any comments on my feed

**Comment by mcaci** [comment]
I see, no problem, I will paste it here just below:

Well, it depends much on the context where HashMap is created and used.
In the current situation, inside the same package, we agree that we can use both New and HashMap{...} to initialize its fields.
However, since these fields are unexported, if we want to call it from an external package we can't modify the fields; they too should be exported to be able to be modified from an external package (in the example of the Server struct in the net/http package this is the case).

So I added the NewWith to be able to customize the HashMap from outside the package, I changed the package inside hashmap_test.go to dynamic_test to test the code from outside the package.

I can revert these change to have test and code in the same package but it's good that we had this conversation around the NewWith. Let me know your feedbacks and preferences on what to do and I will change accordingly

**Comment by tjgurwara99** [comment]
> However, since these fields are unexported, if we want to call it from an external package we can't modify the fields; they too should be exported to be able to be modified from an external package

I guess this has become a question of design choice. I think you were right in pointing out that the fields are not exported - I missed that previously so my earlier point about the `net/http` doesn't make sense in this context so I apologise 😅 

I think - after reading through the code thoroughly - you are trying to mimic what `make` keyword does in Go and I think you should replace `NewWith` to `Make` and change the function signature to return an instance of `Hashmap` not a pointer to a `Hashmap` i.e. `func Make(size uint64, capacity uint64) Hashmap` (or something along those lines). I make this distinction because the `new` keyword in the language returns a pointer to an object and `make` returns an instance of the object (map/slice) passed with the desired capacity and size. Thus I think it makes sense to follow this pattern - of course this is more of a design question and if you have a suggestion and want to argue against this, just tag me. I'm more than happy to discuss `Go` topics and idioms 😄

**Comment by mcaci** [comment]
Hi @tjgurwara99, thanks for your feedback. It's good that we discussed about this, it was helpful to learn for many things. I see your point in my function `NewWith` to behave similarly to `make` and I agree with your suggestion to change it to `Make` and return the struct itself. I have done the update, thanks again for sharing your thoughts!

**Comment by tjgurwara99** [comment]
I think you've overwritten everything that you did in the PR and rebased to a previous state. Try to revert your last commits and I'll see if it gets reverted back. This happens because you seem to rebase your source instead of committing line by line but try to be careful because you can loose a lot of information by doing that or try not to rebase them to previous states for your commits.

**Comment by mcaci** [comment]
Hi, yes I didn't see it and I did a bad mistake on this PR. I created a new one (#435) to start fresh. I apologise for this mistake. I learned to be more careful next time to see that I don't overwrite anything.

**Comment by tjgurwara99** [comment]
> Hi, yes I didn't see it and I did a bad mistake on this PR. I created a new one (#435) to start fresh. I apologise for this mistake. I learned to be more careful next time to see that I don't overwrite anything.
> 
> If you're ok I will close this one and keep the review going on #435.

That's fine - I'll look at it now. If this keeps happening to you, its worth looking at your `.gitconfig` in your home directory - this is your global configurations and you can configure it to however you use it 😄 there might be a setting that you might have set for `commit` flag for `git`.

**Pull request closed without merging**
