### PR TITLE
fiz/issue

### PR DESCRIPTION
**Pull request by Relesi**

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
Please pull changes from the latest master so that your changes can be seen and not 15 files from previous commits

**Comment by raklaptudirm** [comment]
@siriak They are actually pushing changes from `master` into `style_guide`.

**Review by siriak — APPROVED** [review]
Ha, I missed that, my bad :)

**Comment by siriak** [comment]
Can I merge this?

**Comment by raklaptudirm** [comment]
@siriak We are still working on the style guide, so we can delay this.

**Comment by tjgurwara99** [comment]
@Relesi please provide a description of what this PR is for. I don't see any benefit that this PR would have since the branch `style_guide` is already going to be merged. Unless I'm missing any change that you may have made which I doubt since you shouldn't be able to make any changes to any of the branches in this repo unless you fork it.

**Comment by jyzkm** [comment]
邮件已收到，祝好！

**Pull request closed without merging**
