### PR TITLE
feat: Add btree with insertion, deletion, and search

### PR DESCRIPTION
**Pull request by caojoshua**
see https://en.wikipedia.org/wiki/B-tree

### CODE REVIEW

**Comment by caojoshua** [comment]
Could I get a review for this?

**Comment by caojoshua** [comment]
Ping to prevent PR from auto closing. Would still like reviews.

**Review by raklaptudirm — APPROVED** [review]

**Comment by caojoshua** [comment]
Code coverage helped me find bugs where root is null after deleting everything. Added a testcase to handle this case. This should also help with line coverage, but I'm not sure how to check that locally.

**Comment by raklaptudirm** [comment]
Seems you haven't formatted some of the changed files, please do so.

**Review by raklaptudirm — APPROVED** [review]

**Pull request merged**
