### PR TITLE
insertion sort: make sorting stable

### PR DESCRIPTION
**Pull request by Daesar**
fix:make insertion sort stable

### CODE REVIEW

**Review by yanglbme — APPROVED** [review]

**Review by raklaptudirm — CHANGES_REQUESTED** [review]
Format your code with `gofmt`.

**Comment by Daesar** [comment]
> Format your code with `gofmt`.

ok, finished

**Review by raklaptudirm — DISMISSED** [review]

**Review by siriak — DISMISSED** [review]

**Comment by Daesar** [comment]
> Format your code with `gofmt`.

I have run `gofmt -s insertion sort.go`,but still  Error: File is not `gofmt`-ed with `-s` (gofmt).why?

**Comment by raklaptudirm** [comment]
@Daesar That is not a problem with your code. Don't worry about it.

**Comment by Daesar** [comment]
> @Daesar That is not a problem with your code. Don't worry about it. Also remove your latest commit.
Thx,I have removed.

**Review by raklaptudirm — DISMISSED** [review]

**Review by raklaptudirm — APPROVED** [review]

**Review by siriak — APPROVED** [review]

**Pull request merged**
