### PR TITLE
Center of the circle

### PR DESCRIPTION
**Pull request by i-redbyte**
Find the center of the circle.

### CODE REVIEW

**Comment by raklaptudirm** [comment]
In my opinion, this is a trivial algorithm.

**Comment by i-redbyte** [comment]
> In my opinion, this is a trivial algorithm.

Simple algorithms are they also algorithms?
https://github.com/TheAlgorithms/Go/blob/master/math/pythagoras/pythagoras.go - there is also a simple algorithm here. And I also wanted to add that this is just a blank in which it is planned to add more complex algorithms.

**Comment by raklaptudirm** [comment]
By trivial, I mean the following:
- It is extremely simple.
- It does not serve any important purpose.
- There is nothing to understand in it.

I will of course wait for the other maintainers opinions.

**Review by siriak — COMMENTED** [review]
I wouldn't include that since it's too simple. Not that it's not an algorithm, but we cannot include everything because it'll be difficult to navigate the repository if we do so. Most people won't look for an implementation of this algorithm since they can write one by themselves in no time.

**Comment by siriak** [comment]
Seems that the maintainers are on the same page on this issue, so I'm closing this PR. Sorry that this algorithm wasn't accepted, have a good day, and I hope to see contributions that align with our values from you!

**Pull request closed without merging**
