### PR TITLE
bug fix for AddAtBeg

### PR DESCRIPTION
**Pull request by leoliuasia**
AddAtBeg missing prev for old node

### CODE REVIEW

**Comment by AmaterasuOmikami** [comment]
I also found this bug, I managed to see that you fixed it, before making my own pull request, thx :smiley_cat:

**Review by iamrajiv — APPROVED** [review]

**Review by siriak — APPROVED** [review]
LGTM, thanks!

**Comment by siriak** [comment]
Could you resolve conflicts so that I could merge?

**Comment by tjgurwara99** [comment]
This has been fixed I think. See [this](https://github.com/TheAlgorithms/Go/blob/remove_code/data_structures/linkedlist/doubly_linkedlist/doublylinkedlist.go) old branch where the information is present. Because of the restructure, the digging the information of who made that change is very difficult. I'm closing this issue now that this is resolved by someone.

**Pull request closed without merging**
