### PR TITLE
chore: update `codecov-action` to `v4`

### PR DESCRIPTION
**Pull request by vil02**
Same as TheAlgorithms/Rust#670 - it contains the description of the problem.

~~Before merging, please add the token from https://app.codecov.io/gh/TheAlgorithms/Go/settings as `CODECOV_TOKEN` into the repo secrets.~~ [Token was added](https://github.com/TheAlgorithms/Go/pull/704#pullrequestreview-2012231840).

### CODE REVIEW

**Comment by jyzkm** [comment]
邮件已收到，祝好！

**Comment by vil02** [comment]
Please 'dont-close' or merge.

**Review by siriak — APPROVED** [review]
I have added the token. Is it ready to be merged?

**Comment by vil02** [comment]
> Is it ready to be merged?

From my side: yes.

**Pull request merged**
