### PR TITLE
Removed main from all sort functions, changed packages to "sorts" package

### PR DESCRIPTION
**Pull request by c4llmeco4ch**
Other than minor changes made to files to deal with a removed main function, this should help to deal with #37 . I have tests I'm currently working on and we should remove some of the files that are duplicates as referenced in #99 , as this leads to build issues.

As an aside, I don't know enough about topological sort to know how to rework the algorithm so I simply commented out main and someone else might need to go back in and condense the program to accommodate.

### CODE REVIEW

**Comment by cclauss** [comment]
Consistency in file naming?
* Heapsort.go --> heap_sort.go
* InsertionSort.go --> insertion_sort.go
* SelectionSort.go --> selection_sort.go
* TopologicalSort.go --> topological_sort.go

Add a __test_sorts.go__ file that tests all of the sorts with the same test data and also prints side-by-side benchmarks of the various sort algorithms.

**Comment by c4llmeco4ch** [comment]
Fixed the naming issue. Added the beginning of a test suite. Will add tests but wanted to get this out the door as the start of something bigger

**Comment by c4llmeco4ch** [comment]
Should now be noted resolving this PR also deals with #99

**Comment by cclauss** [comment]
Cool.  It would also be helpful is you could remove __|| true__ from the end of https://github.com/TheAlgorithms/Go/blob/master/.github/workflows/golangci-lint.yml#L21 and still have the tests passing.

**Comment by c4llmeco4ch** [comment]
Done!

**Comment by c4llmeco4ch** [comment]
I'm working on a different PR/branch that can be merged with the remainder of the tests presently. I'll also need to update some of the algorithms to actually return slices. Those can be completed in the other PR as well since they're all testing-related.

**Comment by c4llmeco4ch** [comment]
Just wanted to check in and see if there was anything else that'd be ideal for this PR. See the above comment in regards to a separate PR for tests/updating return values

**Comment by cclauss** [comment]
OK @c4llmeco4ch this is landed but it breaks the GitHub Actions build so we need your followup PR that both tests and benchmarks all of these sort routines.  That PR must get the GitHub Actions to be green again so that others can have confidence in contributing to this repository.

**Comment by c4llmeco4ch** [comment]
Went ahead and set up #102 . There's a major issue regarding Topological Sort that's causing problems, so up to you on how you want to tackle it. I'm game to fix it all in one swing but that will take time. Alternatively, we can patch it up, get it working, then take extra time in a third PR to fix whatever needs to happen for Topological sort.

**Pull request merged**
