### PR TITLE
Refactored comments to comply with godocs

### PR DESCRIPTION
**Pull request by 11-aryan**
Removed line breaks and made small changes to the comments

### CODE REVIEW

**Review by raklaptudirm — CHANGES_REQUESTED** [review]
Seems the stack array changes are also bundled inside this pr.

**Comment by 11-aryan** [comment]
I guess I should have created a new branch instead of a sub branch. How can that be fixed now?

**Comment by raklaptudirm** [comment]
You should create a new branch from `master`, re-commit the changes, and open a new pr.

**Comment by 11-aryan** [comment]
Okay, will do.

**Comment by 11-aryan** [comment]
I created a new branch, but still it's merging with the old one, can anyone please help me with this ?

**Pull request closed without merging**
