### PR TITLE
Backtracking algorithms added

### PR DESCRIPTION
**Pull request by Shivam010**

### CODE REVIEW

**Comment by tjgurwara99** [comment]
Please take a look at the [contributing guidelines](https://github.com/TheAlgorithms/Go/blob/d2f12849df76203d80762ceca5105531d3424384/CONTRIBUTING.md) and make changes accordingly. Currently this PR is not up to standard. If no changes are made in the next two weeks, I will consider this PR to be stale and will close this PR then.

**Comment by Shivam010** [comment]
It took 3 years for someone to look at it. I have forgotten about the PR. I'll look into it.

**Comment by raklaptudirm** [comment]
Well, I think you will have a better reviewing experience from now onwards. We now have three active maintainers for the repo and hope such issues will not arise again.

**Comment by Shivam010** [comment]
Closing this wrt #349

**Pull request closed without merging**
