### PR TITLE
feat: dijkstra closest distance implementation

### PR DESCRIPTION
**Pull request by ongspxm**

### CODE REVIEW

**Comment by tjgurwara99** [comment]
As said earlier, there are conflicts that appeared after the last merge. I recommend going over the steps that Github recommends to manually resolve all the conflicts. You should be able to see a `Resolve Conflicts` button here below and it will show you steps to resolve them manually. If you need any help, let me know and I can potentially direct you to a gitpod instance for how to solve these.

**Comment by ongspxm** [comment]
my bad, my branch might have been messy, i tried again, let me know if this works

**Review by siriak — DISMISSED** [review]

**Review by raklaptudirm — DISMISSED** [review]

**Comment by raklaptudirm** [comment]
@tjgurwara99 Your review please.

**Review by tjgurwara99 — CHANGES_REQUESTED** [review]

**Comment by ongspxm** [comment]
i made the necessary changes, but regarding the recursive, i am not sure how to go about doing it without making the heap usage unnecessarily complex. however, i did refactored out some of the logic so that the abstraction is abit clearer

**Review by tjgurwara99 — APPROVED** [review]

**Review by raklaptudirm — APPROVED** [review]

**Pull request merged**
